apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - configmap.yaml

commonLabels:
  app: portfolio
  managed-by: kustomize

images:
  - name: 160806393258.dkr.ecr.us-east-2.amazonaws.com/portfolio
    newTag: latest

configMapGenerator:
  - name: portfolio-config
    files:
      - nginx.conf

replicas:
  - name: portfolio
    count: 3
